[package]
name = "dive-deco"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A dive decompression models library (Buehlmann ZH-L 16 C)"
keywords = ["deco", "decompression", "Buehlmann", "scuba", "diving"]
categories = ["algorithms", "simulation", "science"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
